version: '3'
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: git-sonarr-stack
    env_file: ./myenvs.env
    environment:
      - TZ=${TZENV}
      - PUID=0
      - PGID=0
      - UMASK=002
    volumes:
      - ${SONCONFIG}:/config
      - ${PLEXTV}:/download/tv 
    restart: always
    network_mode: container:homarr-stack
    labels:
      - homepage.group=Media
      - homepage.name=Sonarr
      - homepage.icon=sonarr.png
      - homepage.href=http://10.10.20.200:8989
      - homepage.description=TV Media Download

  radarr:
    image: linuxserver/radarr:latest
    container_name: git-radarr-stack
    env_file: ./myenvs.env
    environment:
      - TZ=${TZENV}
      - PUID=0
      - PGID=0
      - UMASK=002
    volumes:
      - ${RADCONFIG}:/config
      - ${PLEXMOVIES}:/download/movies 
    restart: always
    network_mode: container:homarr-stack
    labels:
      - homepage.group=Media
      - homepage.name=Radarr
      - homepage.icon=radarr.png
      - homepage.href=http://10.10.20.200:7878/
      - homepage.description=Movie Media Download

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: git-prowlarr-stack
    env_file: ./myenvs.env
    environment:
      - TZ=${TZENV}
      - PUID=0
      - PGID=0
      - UMASK=002
    volumes:
      - ${PROWLCONFIG}:/config
    network_mode: container:homarr-stack
    restart: always

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: git-bazarr
    env_file: ./myenvs.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /srv/datastore/docker/bazarr:/config
      - ${PLEXMOVIES}:/movies #optional
      - ${PLEXTV}:/tv #optional
    network_mode: container:homarr-stack
    restart: always

networks:
  MyMacvlan:
    external: true
    name: MyMacvlan
